version: "3.8"
services:
  fluent:
    image: fluent/fluentd:edge
    volumes:
      - ./conf/test.conf:/fluentd/etc/test.conf
    environment:
      FLUENTD_CONF: test.conf
    ports:
      - 5170:5170
  mlsearch:
    image: getmeili/meilisearch
    ports:
      - 7700:7700
  adapter:
    build:
      context: .
      dockerfile: Dockerfile.fd
    ports:
      - 9000:9000
    environment:
      DB_ADDR: http://mlsearch:7700
    depends_on:
      - fluent
      - mlsearch