version: "3.8"
services:
  mlsearch:
    image: getmeili/meilisearch
    ports:
      - 7700:7700
  adapter:
    build: .
    ports:
      - 5170:5170
    environment:
      DB_ADDR: http://mlsearch:7700
    depends_on:
      - mlsearch