version: "3.8"
services:
  mlsearch:
    image: getmeili/meilisearch
    ports:
      - 7700:7700
  adapter:
    image: polyse/fadapter
    ports:
      - 9000:9000
    environment:
      DB_ADDR: http://mlsearch:7700
    depends_on:
      - mlsearch