// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/polyse/logdb/internal/adapter"
	"github.com/polyse/logdb/internal/api"
)

// Injectors from wire.go:

func initLogAdapterApi(ctx context.Context, c *config, ch chan<- error) (*api.API, func(), error) {
	apiConfig := createApiConfig(c)
	adapterConfig := createLogAdapterConfig(c)
	simpleAdapter, err := adapter.NewAdapter(adapterConfig)
	if err != nil {
		return nil, nil, err
	}
	apiAPI, cleanup, err := api.NewAdapterApi(ctx, apiConfig, simpleAdapter, ch)
	if err != nil {
		return nil, nil, err
	}
	return apiAPI, func() {
		cleanup()
	}, nil
}
