// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Adapter is an autogenerated mocks type for the Adapter type
type Adapter struct {
	mock.Mock
}

// DatabaseHealthCheck provides a mocks function with given fields:
func (_m *Adapter) DatabaseHealthCheck() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveData provides a mocks function with given fields: data, indexUid
func (_m *Adapter) SaveData(data []byte, indexUid string) error {
	ret := _m.Called(data, indexUid)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, string) error); ok {
		r0 = rf(data, indexUid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
