// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	meilisearch "github.com/senyast4745/meilisearch-go"
	mock "github.com/stretchr/testify/mock"
)

// APIStats is an autogenerated mocks type for the APIStats type
type APIStats struct {
	mock.Mock
}

// Get provides a mocks function with given fields: indexUID
func (_m *APIStats) Get(indexUID string) (*meilisearch.StatsIndex, error) {
	ret := _m.Called(indexUID)

	var r0 *meilisearch.StatsIndex
	if rf, ok := ret.Get(0).(func(string) *meilisearch.StatsIndex); ok {
		r0 = rf(indexUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.StatsIndex)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(indexUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mocks function with given fields:
func (_m *APIStats) GetAll() (*meilisearch.Stats, error) {
	ret := _m.Called()

	var r0 *meilisearch.Stats
	if rf, ok := ret.Get(0).(func() *meilisearch.Stats); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.Stats)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
