// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	meilisearch "github.com/meilisearch/meilisearch-go"
	mock "github.com/stretchr/testify/mock"
)

// APIVersion is an autogenerated mock type for the APIVersion type
type APIVersion struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *APIVersion) Get() (*meilisearch.Version, error) {
	ret := _m.Called()

	var r0 *meilisearch.Version
	if rf, ok := ret.Get(0).(func() *meilisearch.Version); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.Version)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
