// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	meilisearch "github.com/senyast4745/meilisearch-go"
	mock "github.com/stretchr/testify/mock"
)

// APIWithIndexID is an autogenerated mocks type for the APIWithIndexID type
type APIWithIndexID struct {
	mock.Mock
}

// Client provides a mocks function with given fields:
func (_m *APIWithIndexID) Client() meilisearch.ClientInterface {
	ret := _m.Called()

	var r0 meilisearch.ClientInterface
	if rf, ok := ret.Get(0).(func() meilisearch.ClientInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(meilisearch.ClientInterface)
		}
	}

	return r0
}

// IndexID provides a mocks function with given fields:
func (_m *APIWithIndexID) IndexID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
